<!DOCTYPE html>
<html lang="en">  
	<head>
		<meta charset="utf-8">
		<title>MailElephant</title>
		
		<?php 
			$this->headLink()->prependStylesheet("/style/global.css");
			echo $this->headLink();
		?>
		
		<?php 
			$this->headScript()->prependFile("/script/global.js");
			$this->headScript()->prependFile("/script/jquery-1.7.2.min.js");
			echo $this->headScript();
		?>
	</head>
	<body>
	
		<div id="Header">
			<h1>MailElephant</h1>
		</div>
		
		<div id="Menu">
			<ul>
				<li>
					<a href="/lists">lists</a>
					<ul>
						<li>
							<a href="/lists/create">create list</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="/newsletters">newsletters</a>
					<ul>
						<li>
							<a href="/newsletters/add">upload email</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="/campains">campains</a>
					<ul>
						<li>
							<a href="/campains/create">create</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="/user">Account</a>
					<ul>
						<li>
							<a href="/user/edit">edit my data</a>
						</li>
					</ul>
				</li>
			</ul>
		</div>
		
		<div id="Content">
			<?php if(!empty($this->flashMessages)): ?>
				<ul id="Messages">
					<?php foreach($this->flashMessages as $message): ?>
						<li><?php echo $message ?></li>
					<?php endforeach; ?>
				</ul>
			<?php endif; ?>
		
	        <?php /* NESTED LAYOUT SUPPORT */ ?> 
	        <?php if($this->layout()->nestedLayout): ?>  
	            <?php $this->layout()->setLayout($this->layout()->nestedLayout); ?> 
	        <?php else: ?> 
	            <?php $this->layout()->setLayout('default'); ?> 
	        <?php endif;?> 
	        <?php echo $this->layout()->render();  ?>
		</div>
		
		<div id="Footer">
			<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
				Logged in as <?php echo Zend_Auth::getInstance()->getIdentity()->getEmail() ?>
			
				<a href="<?php echo $this->url(array('controller'=>"auth", 'action'=>"logout"), null, true) ?>">logout</a>
			<?php else: ?>
				Not logged in 
			<?php endif; ?>
		</div>
	</body>
</html>