<?php $this->headScript()->appendFile("/script/mailboxes.js") ?>

<div id="Mailboxes">
	<ul>
		<?php foreach($this->mailboxes as $mailbox): ?>
			<li>
				<a href="<?php echo $this->url(array('action'=>"open-mailbox", 'mailbox'=>$mailbox->getName())) ?>" class="mailboxOpener">
					<?php echo $mailbox->getName() ?></a>
					
				( <a href="<?php echo $this->url(array('action'=>"mailbox", 'mailbox'=>$mailbox->getName())) ?>">
					edit</a> 
				<form method="post">
					<input type="hidden" name="delete-mailbox" value="<?php echo $mailbox->getName() ?>" />
					<input type="submit" value="delete" />
				</form>)
			</li>
		<?php endforeach; ?>
		<li>
			<a href="<?php echo $this->url(array('action'=>"mailbox")) ?>">
				define a mailbox</a>
		</li>
	</ul>
</div>

<div id="MailboxMessages">
	<p class="loadingMessage">opening mailbox...</p>
	<table>
		<thead>
			<tr>
				<th>from</th>
				<th>subject</th>
			</tr>
		</thead>
		<tbody></tbody>
	</table>
</div>

<p>
</p>

<?php echo $this->form ?>