<?php $this->layout()->nestedLayout = 'newsletter-add-toolbar' ?>

<?php $this->headScript()->appendFile("/script/mailboxes.js") ?>

<div id="Mailboxes">
	<ul>
	<?php foreach($this->mailboxes as $mailbox): ?>
		<li>
			<a href="<?php echo $this->url(array('action'=>"open-mailbox", 'mailbox'=>$mailbox->getMailbox())) ?>" class="mailboxOpener">
				<?php echo $mailbox->getMailbox() ?></a>
				
			( <a href="<?php echo $this->url(array('action'=>"mailbox", 'mailbox'=>$mailbox->getMailbox())) ?>">
				edit</a> )
		</li>
	<?php endforeach; ?>
	</ul>
</div>

<div id="MailboxMessages">
	<p class="loadingMessage">opening mailbox...</p>
	<table>
		<thead>
			<tr>
				<th>from</th>
				<th>subject</th>
			</tr>
		</thead>
		<tbody></tbody>
	</table>
</div>

<p>
	<a href="<?php echo $this->url(array('action'=>"mailbox")) ?>">
		define a mailbox</a>
</p>

<?php echo $this->form ?>