<table>
	<thead>
		<tr>
			<th>date</th>
			<th>subject</th>
			<th># attachments</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<?php 
		foreach($this->newsletters as $newsletter):
			/* @var $newsletter Newsletter_Model_Newsletter */ 
	?>
		<tr>
			<td><?php echo $newsletter->hasCreationDate() ? $newsletter->getCreationDate()->format('c') : "?" ?></td>
			<td><?php echo $newsletter->getSubject() ?></td>
			<td><?php echo $newsletter->getNumAttachments() ?></td>
			<td>
				<a href="<?php echo $this->url(array('action'=>"view", 'newsletterid'=>$newsletter->getId())) ?>">
					view</a>
				<a href="<?php echo $this->url(array('action'=>"edit", 'newsletterid'=>$newsletter->getId())) ?>">
					edit</a>
				<form action="" method="post">
					<input type="hidden" name="delete-newsletterid" value="<?php echo $newsletter->getId() ?>" />
					<input type="submit" value="delete" />
				</form>
				<a href="<?php echo $this->url(array('controller'=>"campains", 'action'=>"create", 'newsletterid'=>$newsletter->getId())) ?>">
					create campain</a>
			</td>
		</tr>
	<?php
		endforeach; 
	?>	
	</tbody>
</table>	