<h1><?php echo count($this->subscribtions) ?> subscribtions</h1>

<table>
	<thead>
		<tr>
			<th>name</th>
			<th>email</th>
			<th>group</th>
		</tr>
	</thead>
	<tbody>
	<?php 
		foreach($this->subscribtions as $subscribtion):
			/* @var $subscribtion Newsletter_Model_Subscribtion */ 
	?>
		<tr>
			<td><?php echo $subscribtion->getName() ?></td>
			<td><?php echo $subscribtion->getEmail() ?></td>
			<td><?php echo $subscribtion->getGroup()->getTitle() ?></td>
		</tr>
	<?php endforeach;?>
	</tbody>
</table>