<ul class="actions">
	<li>
		<a href="<?php echo $this->url(array('action'=>"create")) ?>">create new campain</a>
	</li>
</ul>

<table>
	<thead>
		<tr>
			<th>date</th>
			<th>newsletter subject</th>
			<th>status</th>
			<th>error/sent/total</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->campains as $campain): ?>
			<tr>
				<td>
					<?php echo $campain->getCreationDate()->format("j M Y H:i") ?>				
				</td>
				<td><?php echo $campain->getNewsletterSubject() ?></td>
				<td>
					<?php if($campain->isCompleted()): ?>
						Completed
					<?php elseif($campain->isPaused()): ?>
						Paused
					<?php else: ?>
						Sending
					<?php endif; ?>
				</td>
				<td>
					<?php if($campain->getNumErrorSendingItems() > 0): ?>
						<a href="<?php echo $this->url(array('action'=>"view-errors", 'campain'=>$campain->getId())) ?>"><?php echo $campain->getNumErrorSendingItems() ?></a>
					<?php else: ?>
						0
					<?php endif; ?>
					/ <?php echo $campain->getNumSentSendingItems() ?>
					/ <?php echo $campain->getNumSendingItems() ?>
				</td>
				<td>
					<?php if(!$campain->isCompleted()): ?>
						<form method="post">
							<?php if($campain->isPaused()): ?>
								<input type="hidden" name="unpause" value="<?php echo $campain->getId() ?>" />
								<input type="submit" value="Unpause" class="actionButton" />
							<?php else: ?>
								<input type="hidden" name="pause" value="<?php echo $campain->getId() ?>" />
								<input type="submit" value="Pause" class="actionButton" />
							<?php endif; ?>
						</form>
					<?php endif; ?>
				</td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>