<!DOCTYPE html>
<html lang="en">  
	<head>
		<meta charset="utf-8">
		<title>MailElephant</title>
		
		<?php 
			$this->headLink()->prependStylesheet("/style/global.css");
			echo $this->headLink();
		?>
		
		<?php 
			$this->headScript()->prependFile("/script/global.js");
			$this->headScript()->prependFile("/script/jquery-1.7.2.min.js");
			echo $this->headScript();
		?>
	</head>
	<body>
	
		<div id="Header">
			<h1>MailElephant</h1>
		</div>
		
		<div id="Menu">
			<ul>
				<li>
					<a href="/subscribtions">subscribtions</a>
				</li>
				<li>
					<a href="/newsletters">newsletters</a>
					<ul>
						<li>
							<a href="/newsletters/add">upload email</a>
						</li>
					</ul>
				</li>
			</ul>
		</div>
		
		<div id="Content">
	        <?php /* NESTED LAYOUT SUPPORT */ ?> 
	        <?php if($this->layout()->nestedLayout): ?>  
	            <?php $this->layout()->setLayout($this->layout()->nestedLayout); ?> 
	        <?php else: ?> 
	            <?php $this->layout()->setLayout('default'); ?> 
	        <?php endif;?> 
	        <?php echo $this->layout()->render();  ?>
		</div>
	</body>
</html>