<ul class="actions">
	<li>
		<a href="<?php echo $this->url(array('action'=>"import-subscribtions")) ?>">add subscribtions from file</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array('action'=>"create-subscribtion")) ?>">create new subscribtion</a>
	</li>
</ul>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Emailaddress</th>
			<th>Added</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php 
			foreach($this->subscribtions as $subscribtion):
				/* @var $subscribtion MailElephantModel_Subscibtion */ 
		?>
			<tr>
				<td><?php echo $subscribtion->getName() ?></td>
				<td><?php echo $subscribtion->getEmail() ?></td>
				<td><?php echo $subscribtion->getAdded()->format("d-m-Y H:i") ?></td>
				<td>
					<form method="post">
						<input type="hidden" name="delete-subscribtion" value="<?php echo $subscribtion->getEmail() ?>" />
						<input type="submit" value="delete" />
					</form>
				</td>
			</tr>
		<?php endforeach; ?>		
	</tbody>
</table>

