<p>
	<a href="<?php echo $this->url(array('action'=>"import-subscribtions")) ?>">import subscribtions</a>
	<a href="<?php echo $this->url(array('action'=>"create-subscribtion")) ?>">create subscribtion</a>
</p>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Emailaddress</th>
		</tr>
	</thead>
	<tbody>
		<?php 
			foreach($this->subscribtions as $subscribtion):
				/* @var $subscribtion MailElephantModel_Subscibtion */ 
		?>
			<tr>
				<td><?php echo $subscribtion->getName() ?></td>
				<td><?php echo $subscribtion->getEmail() ?></td>
			</tr>
		<?php endforeach; ?>		
	</tbody>
</table>

