<?php $this->layout()->nestedLayout = 'newsletter-add-toolbar' ?>

<?php $this->headScript()->appendFile("/script/mailboxes.js") ?>

<div id="Mailboxes">
	<ul>
	<?php foreach($this->mailboxes as $mailbox): ?>
		<li>
			<a href="<?php echo $this->url(array('action'=>"open-mailbox", 'mailbox'=>$mailbox->getMailbox())) ?>">
				<?php echo $mailbox->getMailbox() ?></a>
		</li>
	<?php endforeach; ?>
	</ul>
</div>

<div id="MailboxMessages">
	<p class="loadingMessage">opening mailbox...</p>
	<ul></ul>
</div>

<p>
	<a href="<?php echo $this->url(array('action'=>"add-mailbox")) ?>">
		define a mailbox</a>
</p>

<?php echo $this->form ?>