<table>
	<thead>
		<tr>
			<th>date</th>
			<th>subject</th>
			<th># attachments</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<?php 
		foreach($this->newsletters as $newsletter):
			/* @var $newsletter Newsletter_Model_Newsletter */ 
	?>
		<tr>
			<td><?php echo $newsletter->getCreated()->format('c') ?></td>
			<td><?php echo $newsletter->getSubject() ?></td>
			<td><?php echo $newsletter->getNumAttachments() ?></td>
			<td>
				<a href="<?php echo $this->url(array('action'=>"view", 'newsletterid'=>$newsletter->getId())) ?>">view</a>
			</td>
		</tr>
	<?php
		endforeach; 
	?>	
	</tbody>
</table>	